### PR TITLE
Change get_metadata to return long-name 

### LINKED ISSUE #25: .get(return_type='id')
```
TypeError: 'EntityEnum' object is not iterable
```

### PR DESCRIPTION
**Pull request by adelavega**
- Fixes #25,
- Handles entities "key" as the name, instead of then "name". E.g. "subject" instead of "sub".
- Update to use DatasetOption in ancpbids

Depends on ancpbids bug fix: https://github.com/ANCPLabOldenburg/ancp-bids/pull/74

### CODE REVIEW

**Comment by adelavega** [comment]
Actually, looks like this is resolved in latest ancpbids version, and now I can get the typical name as before.

**Comment by adelavega** [comment]
TODO: 
- Does `fuzzy_match_entity_key` have long_form--- or translate in `__getattr__`
- Fix `__repr__`

**Comment by effigies** [comment]
I don't understand why you would want to use `display_name`. You have:

```YAML
acquisition:
  name: acq
  display_name: Acquisition
  ...
```

I would want either `acquisition` or `acq` to be used. `Acquisition` only seems useful for rendering.

**Comment by adelavega** [comment]
Yes, you're right. Forgot to change the title but I'm using the normal long name now. Initially couldn't find it in the ancpbids API.

Any opinion on short name vs long name? In vote long name to be consistent w prior API

**Comment by adelavega** [comment]
I added adelavega/ancpbids as the requirement pinned, to be able  to merge this

**Pull request merged**
